---

writeGraphs: false
writeGraphsDot: false

contexts:
  main:
    instrument: false
    #instrumentUser: imagemagick
    #instrumentCoverage: true
    #mprotect_mode: true
    selectors:
      - "*.o"
      - "libMagick*.a"
    function_behavior:
      AcquireMagickMemory: malloc
      RelinquishMagickMemory: free
  library:
    selectors:
      - "libgs.so"
      #- "libpng16.so"
    permissions:
      readonly:
        #- /bin
        #- /lib
        #- /lib64
        #- /sbin
        #- /usr
        #- /etc
        - /dev/urandom
        - $HOME/Projekte/ipcprototype/demos/ghostscript  # TODO REMOVE IN RELEASE
        - /var/lib/ghostscript
        - /usr
      readwrite:
        - "$ARGV_FOLDERS"
        - /tmp
      #user: 65534 # = nobody
      #group: 65534 # = nogroup
      # network: all/host, local, none
      network: none
